repository:
  description: A Google Cloud Build configuration file that you can drop into your repository to speed up builds by leveraging Google Container Registry as a remote build cache
  topics: google-cloud-build cloudbuild cloud-build docker
  private: false
  has_projects: false
  has_wiki: false
  default_branch: master

branches:
  - name: master
    protection:
      required_pull_request_reviews:
        require_code_owner_reviews: true
        dismiss_stale_reviews: true
      required_status_checks:
        strict: true
        contexts:
        - YAMBURGER
        - Build
        - WIP
      restrictions: null
